version: "2"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/opt/netmanager:Z
    ports:
      - "6543:6543"
    links:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=21kill22
